- label: "Ceiling light"
  prompt: "Good looking room with only one lamp on the ceiling"
  scale: 0.3
  y_pos: 0.0
- label: "Embedded ceiling lamp"
  prompt: "Good looking room with only one embedded lamp in the ceiling"
  scale: 0.2
  y_pos: 0.2
- label: "Bed lamp"
  prompt: "Lamp on the cupboard beside the bed"
  scale: 0.5
  y_pos: 0.5
- label: "Desk lamp"
  prompt: "Lamp on the desk"
  scale: 0.5
  y_pos: 0.4
- label: "Indoor pillar light designed to be mounted on the wall"
  prompt: "Indoor wall mounted light"
  scale: 0.5
  y_pos: 0.5
- label: "Outdoor light designed to be mounted on the wall, not prolongated, not tall, small"
  prompt: "Lamp mounted to the brick wall in the garden"
  scale: 0.5
  y_pos: 0.3
- label: "Outdoor column light, ground mounted, prolongated, tall"
  prompt: "Outdoor column light mounted to the ground"
  scale: 0.75
  y_pos: 0.8

- label: "Grill"
  prompt: "Grill in the grill area in the garden"
  scale: 0.75
  y_pos: 0.5
- label: "Swimming pool"
  prompt: "Swimming pool in the backyard"
  scale: 0.75
  y_pos: 0.5
- label: "Outdoor table"
  prompt: "Garden table on tile floor"
  scale: 0.5
  y_pos: 0.7
- label: "Outdoor chair, not prolongated"
  prompt: "Garden chair on tile floor"
  scale: 0.5
  y_pos: 0.7
- label: "Outdoor chaise lounge, prolongated chair"
  prompt: "Chaise lounge in the garden"
  scale: 0.75
  y_pos: 0.8
- label: "Garden furniture"
  prompt: "Furniture in the garden"
  scale: 0.75
  y_pos: 0.